%% DO NOT EDIT this file manually; it was automatically
%% generated from `Documentation/snippets/new/`.
%%
%% Make any changes in `Documentation/snippets/new/`,
%% then run `scripts/auxiliar/makelsr.pl --new`.
%%
%% This file is in the public domain.
%%
%% Note: this file needs at least LilyPond version 2.25.35.

\version "2.25.80"

\header {
  categories = "Rhythms"

  texidoc = "
Normally, LilyPond refuses to automatically break a line at places
where a beam crosses a bar line. This behavior can be changed by
setting the @code{Beam.breakable} property to @code{#t}.

This property does not affect manual breaks inserted with commands like
@code{\\break}.
"

  doctitle = "Beams across line breaks"
} % begin verbatim


music = {
  \*8 c8
  c8 \*7 { c[ c] }  c
  \*8 c8
}

\relative c'' {
  <>^\markup { \typewriter Beam.breakable set to \typewriter "#t" }
  \override Beam.breakable = ##t
  \music
}

\relative c'' {
  <>^\markup { \typewriter Beam.breakable not set }
  \music
}

\paper {
  line-width = 100\mm
}
