%% DO NOT EDIT this file manually; it was automatically
%% generated from `Documentation/snippets/new/`.
%%
%% Make any changes in `Documentation/snippets/new/`,
%% then run `scripts/auxiliar/makelsr.pl --new`.
%%
%% This file is in the public domain.
%%
%% Note: this file needs at least LilyPond version 2.24.0.

\version "2.24.0"

\header {
  categories = "Expressive marks, Really simple, Text"

  texidoc = "
Some dynamics may involve text indications (such as @qq{più @emph{f}} or
@qq{@emph{p} subito}). These can be produced using a @code{\\markup}
block; the resulting object behaves like a @code{TextScript} grob.

See also @qq{Combining dynamics with markup texts (2)}.
"

  doctitle = "Combining dynamics with markup texts"
} % begin verbatim


piuF = \markup { \italic più \dynamic f }

\score {
  \relative c'' {
    c2\f c-\piuF
  }
}
